### ISSUE TITLE
Offer UI feedback on indexing

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#101]
We have this indexing progress monitor. However, the embedding doesn't seem to be part of it?

![image](https://github.com/user-attachments/assets/c5285cd1-874c-4f64-a30d-905b12fd5411)

**Comment by InAnYan** [comment]
According to Carl, there is a way to show users the background task (`showToUser(boolean)`), but there is no way to remove background task from progress monitor, once it's completed :)

What should we do? I think this issue connects not only to my AI PR, but to the whole JabRef (about removing background task)

**Comment by InAnYan** [comment]
Should be done.

Check, do you like it?

If you see that the task is not gone in progress indicator, then refer to https://github.com/InAnYan/jabref/issues/101#issuecomment-2267402766

**Comment by koppor** [comment]
> According to Carl, there is a way to show users the background task (`showToUser(boolean)`), but there is no way to remove background task from progress monitor, once it's completed :)

Just for tracking. It is a [ControlfsFX control](https://github.com/controlsfx/controlsfx). One needs to work on that. Or on its usage in JabRef.

**Comment by koppor** [comment]
Looks better:

![image](https://github.com/user-attachments/assets/e915891b-6f79-433f-ab2c-1a77f7b277b0)

The text "57% work done ..." is a text mirroring the title and the progress bar. That should be removed.
(If you keep it, all other progress bar texts need to be adapted. For consistency)

**Comment by InAnYan** [comment]
Hey, here is the "downloading embedding model" :laughing:

**Comment by InAnYan** [comment]
I removed it.

I think you can close this issue, and then answer me at: https://github.com/InAnYan/jabref/issues/115#issuecomment-2268676089

**Comment by koppor** [comment]
I'll close with the hope, you can address everything at once ^^
