### ISSUE TITLE
Handle request too large

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#102]
> 429 - message: Request too large for gpt-4o in organization org-3M84iZQTliRuKpVVeuB53iHJ on tokens per min (TPM): Limit 30000, Requested 49292. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more., type: tokens, param: null, code: rate_limit_exceeded

![image](https://github.com/user-attachments/assets/2426e7c4-b071-416b-9f00-8b87252ed5d7)

Retry with the split approach then?

**Comment by InAnYan** [comment]
That's strange, it should've retried with splitting approach.

@koppor, when you have time, could you attach me a PDF with this issue?

**Comment by koppor** [comment]
Additionally, the error message maybe should contain the file name. That could help to remember which PDF was used.

**Comment by InAnYan** [comment]
OMG, it seems I'm splitting documents, but instead passing a full document to AI. Working on it

**Comment by InAnYan** [comment]
@koppor, when you have time, try to load the document again. Should work now

**Comment by koppor** [comment]
Yeah, looks good:

![image](https://github.com/user-attachments/assets/2482e709-4c24-4aef-955d-4681d54e409d)
