### ISSUE TITLE
Show progress while embedding model is downloaded

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#105]
As user, I do not see any progress or output what is downloaded from where. I remember that I once saw the URLs somewhere, but as of today, they are not shown at all.

![image](https://github.com/user-attachments/assets/1ad70661-903b-41d0-a2ee-3e11640aaa3f)

- (2): Please show the background task progress for embedding model downloading
- (1): Please rename to "Downloading embedding model... Afterwards, you will be able to chat with your files."

**Comment by InAnYan** [comment]
Should be done.

Check, do you like it?

If you see that the task is not gone in progress indicator, then refer to https://github.com/InAnYan/jabref/issues/101#issuecomment-2267402766

**Comment by InAnYan** [comment]
Done, can you check?

If you see that the task is not gone in progress indicator, then refer to https://github.com/InAnYan/jabref/issues/101#issuecomment-2267402766

**Comment by koppor** [comment]
> Done, can you check?

Pulled now.

Not in the list of tasks:

![image](https://github.com/user-attachments/assets/ccb19ccf-f97f-44da-8ce4-134f00249585)

> If you see that the task is not gone in progress indicator, then refer to [#101 (comment)](https://github.com/InAnYan/jabref/issues/101#issuecomment-2267402766)

Fixed via https://github.com/JabRef/jabref/pull/11574, which is merged in main.

**Comment by InAnYan** [comment]
Okay, you can now recheck it.

It should work...

**Comment by koppor** [comment]
Does not work:

![image](https://github.com/user-attachments/assets/8b70f14d-1451-4832-93f1-3e0bc95737ed)

**Comment by koppor** [comment]
![image](https://github.com/user-attachments/assets/a0c83624-68bc-44e2-8e01-badc8b7af45d)

**Comment by InAnYan** [comment]
I think I understood why this happens.

This should be fixed in a recent push :)

**Comment by koppor** [comment]
Download log is there - seems to happen even before the user saved the preferences. 

![image](https://github.com/user-attachments/assets/3260bed2-c63d-4f85-b5ac-757d58260cf2)

**Comment by koppor** [comment]
> That's might be because you switched on "Enable AI"

I think so, too. I think, because of these observables. Something is wrong in their use.

Settings take effect after calling `org.jabref.gui.preferences.PreferencesTab#storeSettings`. Before, the settings do not take effect. - Normally, this is no issue, because no external actions are triggered. In your case, we see that bad consequences.

I checked the "cancel" button. If I reload the preferences, at least the provider URL is reverted back. Thus, this part is OK.

**Comment by InAnYan** [comment]
What should I do for this feature more?

You don't see background task progress indication?

**Comment by koppor** [comment]
Checked on Linux Mint 21. Seems to work. I will reopen if I encounter the issue again.
