### ISSUE TITLE
Add summarization to user-visible background tasks

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#106]
If I am switching tabs for sumamrization, I expect that each request to summarize is added to the summary queue.

![image](https://github.com/user-attachments/assets/9d1169f9-0e61-4cc2-b902-ec96d073319a)

This is an advanced version of https://github.com/InAnYan/jabref/issues/95.

**Comment by koppor** [comment]
Side note: Interestingly, using the web UI, the summary takes 5 seconds:

![image](https://github.com/user-attachments/assets/f95670a2-ddfb-4372-8cc0-9635ee533ff5)

**Comment by InAnYan** [comment]
Should be done.

Check, do you like it?

If you see that the task is not gone in progress indicator, then refer to https://github.com/InAnYan/jabref/issues/101#issuecomment-2267402766

**Comment by InAnYan** [comment]
For such UI's as OpenAI have, you also need to consider these things:
1. They are "streamed", meaning you get response word by word, so it seems to be fast
2. They also buffer some messages before starting to show word-by-word animation, to hide processing speed. So that also makes it looking fast

**Comment by koppor** [comment]
Currently, it looks like follows:

![image](https://github.com/user-attachments/assets/b7d53114-fac2-4b58-b822-3bef2853d928)

Please remove the text "4% ..." -- Similar to https://github.com/InAnYan/jabref/issues/101#issuecomment-2267633840.

**Comment by InAnYan** [comment]
I removed it.

I think you can close this issue, and then answer me at: https://github.com/InAnYan/jabref/issues/115#issuecomment-2268676089
