### ISSUE TITLE
Handle 404 - null

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#108]
For the summary, I now get "404 - null" as result:_

![image](https://github.com/user-attachments/assets/9ed2511a-16f0-438a-a63a-778eeeffd06c)

There should be some more error output in the log. Currently, there is no log output at all.

**Comment by koppor** [comment]
I think, the reason is that the URL getting is wrong in the code. I commented on the PR.

The current code always reads the URL from the expert settings even though I did not enable expert settings.

**Comment by InAnYan** [comment]
Fixed. I replaced it with a more useful error message.

I think I can close the issue without your recheck, because it's simple
