### ISSUE TITLE
Remove done tasks.

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#109]
The paper "Ding" appears multiple times:

![image](https://github.com/user-attachments/assets/950825c2-bb30-40e7-a8b6-ce0bdf602fe7)

I think, because of https://github.com/InAnYan/jabref/issues/108

This makes the impression that the summary is created multiple times in parallel.

- [ ] After a task is done, it should be removed from the task list. I hope, this is possible with the current task infrastructure.

**Comment by InAnYan** [comment]
Closed, as completed in https://github.com/JabRef/jabref/pull/11574
