### ISSUE TITLE
Replace "Please wait" by "Processing..."

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#111]
JabRef already has the translation string "Processing..."

I think, this should be used instead of "Please wait"

![image](https://github.com/user-attachments/assets/9431598f-4425-46c7-a0d0-01bc7dc09fba)

**Comment by InAnYan** [comment]
![image](https://github.com/user-attachments/assets/acd1a4d1-a7d0-4051-bef3-2db39f40f9f9)

JabRef already uses "Please wait".

So, should I leave "Please wait" or set it to "Processing..."?

**Comment by InAnYan** [comment]
I like "Processing..." more.

However, what should we do when embedding model is downloaded? Let's use "Please wait" there.

I've implemented all I mentioned (AI chat and summarization -> "Processing...", download of embedding model -> "Please wait"). If you think it's okay, then close the issue

**Comment by koppor** [comment]
> I like "Processing..." more.
> 
> However, what should we do when embedding model is downloaded? Let's use "Please wait" there.

+1 for the case-by-case basis.

What about `Downloading...` here? - and in `org.jabref.gui.linkedfile.DownloadLinkedFileAction#doDownload`, also add the three dots to `Downloading` 😅.
