### ISSUE TITLE
The summary window should show when the summary was created with which provider

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#112]
![image](https://github.com/user-attachments/assets/d414aed0-c23a-46dc-8233-f37591ddff67)

- [ ] Timestamp should use the current localization. I think, the hints at https://stackoverflow.com/a/59707272/873282 are good. Try to use [Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html) for representing date and time.

One could also store/log/output the setting used to generated. At least the model maybe?

---

Follow up work could be to switch between the generated summaries (meaning: I can switch between OpenAI, Misral, ...) but this is much requirements work, because the summaries also depend on the model etc...

**Comment by InAnYan** [comment]
Okay, I tried to implement this feature.

Should work. And timestamp should use current locale.

Do you like the look? (Also, clear all JabRef AI related cache before that, because the underlying format is changed)

**Comment by koppor** [comment]
Works!

---

First try - when an existing summary before the upgrade is loaded:

![grafik](https://github.com/user-attachments/assets/f5fab324-65be-4076-aa6e-fc787e992403)

We do not need to implement functionality for that.

`vagrant@lm21vgntbx:~/.local/share/jabref/ai/1$ rm ai.mv `

(Also important for @ThiloteE when trying out a recent build)

**Comment by ThiloteE** [comment]
I have not encountered your error message when running JabRef with a recent build, which is a good thing.
