### ISSUE TITLE
Handle change of citation keys.

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#113]
1. I chat with BibEntry with citationkey `A`.
2. I change the citation key to `B`
3. I reopen the AI chat
4. Chat is empty

Expectation: Chat is the same after step 1.

---

Idea to solve:

1. Listen to entry changed events
2. Filter on citatoin key change
3. Stop if key is changed to something "invalid"
4. get messages for `oldkey`
5. Store messages to `newkey`
6. Remove messages for `oldkey`

**Comment by InAnYan** [comment]
I think I figured it out how to implement it.

But, what if user changes entry to an invalid citation key (empty or non-unique)?

**Comment by InAnYan** [comment]
Okay, I implemented this feature, but the fix doesn't take into account invalid citation keys...

**Comment by koppor** [comment]
Does not work with current pull.

I tried with <kbd>Ctrl</kbd>+<kbd>G</kbd> for generating a new key. (Before, I changed the key pattern to have `abc` at the end).

**Comment by InAnYan** [comment]
1) I've tried to add some letters after the citation key, and it worked
2) I tried Ctrl+G and click on "Generate" button. It worked too

Maybe you had some past push without the change? Could you try again?

@ThiloteE, maybe you can also try this?

**Comment by InAnYan** [comment]
OH NO

I'm sorry, I've only implemented this for chats :laughing:

**Comment by InAnYan** [comment]
Yes. Now it should work
