### ISSUE TITLE
"token" should be renamed to "key"

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#114]
Just fetched an API key from Misral

![image](https://github.com/user-attachments/assets/cb97c8bd-af2b-45b7-8731-7e7053075a17)

JabRef asks for a **token**. IMHO, a key is something different than "token".

I also checked OpenAI. They also talk about "keys". Thus, I propose to rename "token" to "key".

**Comment by InAnYan** [comment]
Fixed in recent push

**Comment by koppor** [comment]
A recent commit introduced "Token" again. Please be consistent in the code and in the UI.  (Scientific reading: "Domain-specific language")

![image](https://github.com/user-attachments/assets/19370bd3-47f2-4d19-9924-ea52c5685cad)

**Comment by ThiloteE** [comment]
Apparently it is only in the code, but not in the UI at commit https://github.com/JabRef/jabref/pull/11430/commits/a38c4398907f60db557c2e033569b92a442b204f:
![image](https://github.com/user-attachments/assets/6bee5b60-191c-4ae7-b588-e9cac54b0c45)

**Comment by koppor** [comment]
> Apparently it is only in the code, but not in the UI at commit https://github.com/JabRef/jabref/pull/11430/commits/a38c4398907f60db557c2e033569b92a442b204f:
> ![image](https://github.com/user-attachments/assets/6bee5b60-191c-4ae7-b588-e9cac54b0c45)
> 

Yes. The domain driven design demands that the terms used in the code are the same as the ones of the UI.

German: Begriffslexikon.

**Comment by InAnYan** [comment]
Yes, I forgot about that.

I changed the code, that API token became API key.

Guess, I can safely close this issue :smile:
