### ISSUE TITLE
Fault-tolerant switch of AI providers

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#117]
1. I configure OpenAI
2. I start chatting
3. I switch to Hugging Face
4. I continue chatting

Expecation: Either JabRef blocks chatting at step 4 - or it works.

Currently:

![image](https://github.com/user-attachments/assets/94dd992c-9aa8-494b-8f36-714ac43651b8)

**Comment by InAnYan** [comment]
Hmm, need to think. It's not really a problem with switching AI providers.

It's a problem of sending requests

**Comment by InAnYan** [comment]
I think we should close this issue, because this is directly related to https://github.com/InAnYan/jabref/issues/118.

And as you can see, in chat history we don't track which AI provider was used. So, those are just plain messages
