### ISSUE TITLE
API base URL is an expert setting? Why can Expert Settings be edited while AI feature is disabled?

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#120]
Why can I change the AOI base URL if there is deactivated "Customize expert settings"?

![image](https://github.com/user-attachments/assets/61321c44-0abe-45a7-bd3d-5700f0251ae5)

**Comment by koppor** [comment]
Happens when the preferences are opened at the first time.

**Comment by InAnYan** [comment]
Should be fixed in a recent push. Could try it out?

**Comment by koppor** [comment]
Thilo said it does not work on the current build

**Comment by InAnYan** [comment]
Strange.....

I can't reproduce it... However when we talked with Thi Lo, I could, and we together retried that.

**Comment by InAnYan** [comment]
Well, should work now...

**Comment by koppor** [comment]
I close. If it does not work for @ThiloteE we can reopen.

**Comment by ThiloteE** [comment]
Works for me.
