### ISSUE TITLE
Cannot select a chat model for Hugging Face

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#121]
![image](https://github.com/user-attachments/assets/5cfb75b4-477e-495a-b421-01fe63f37b48)

Either the field should be disabled - or models should be offered

**Comment by InAnYan** [comment]
You should select models from here https://huggingface.co/models.

And then copy model ID like this: google/gemma-2b from https://huggingface.co/google/gemma-2b.

What's the best way to tell users about this?

1) Disabled - that's not gonna work
2) Models offered - there are nearly 1M models

I propose leaving this in the documentation. If user don't know what to write here, he can just click on help button

**Comment by koppor** [comment]
Use `libraryListView.setPlaceholder(` to guide the user. For text fields you can use `setPrompt`. With that, the UI gets more user friendly.

**Comment by InAnYan** [comment]
That's all?

**Comment by koppor** [comment]
> That's all?

Sometimes, it is easy.
