### ISSUE TITLE
Use "(s)" if not clear if one or more things

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#126]
Currently: "The file was split into 1 chunks"

Replace by "The file was split into 1 chunk(s)".

**Comment by InAnYan** [comment]
Tried to do this in recent push. I'm not sure should I close this issue by myself.

Maybe you can try to look at the AI section in `JabRef_en` (https://github.com/JabRef/jabref/blob/43f1f7c591baa29cb6390dc81fa9a91b453746fd/src/main/resources/l10n/JabRef_en.properties#L2515)?

**Comment by koppor** [comment]
At first sight, it looks good. I will reopen if I see something.
