### ISSUE TITLE
Use quotes for filenames

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#127]
Context: Sometimes, I saw that citation keys are wrapped into single or double quotes. - I would not enclose them in quotes, but maybe it's good for readability. Use double quotes consistently (I saw single quote ones, but don't know where. Too small task to make an issue and to follow-up). 

Please enclose the filename in double quotes so that a fast-reader can identify the filename easily in the log:

![image](https://github.com/user-attachments/assets/b3f54a3c-a85b-4733-8ff2-96d1dac98bbc)

**Comment by InAnYan** [comment]
I'll close this, because while I was working on https://github.com/InAnYan/jabref/issues/95#issuecomment-2269233231, I've done this
