### ISSUE TITLE
Bring back title for background tasks

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#129]
I did not wish to remove all progress text, just the sub title

![image](https://github.com/user-attachments/assets/4658b467-3e84-4517-9e0e-336084b0b8c5)

For summary, it is completely gone. This is not good. Please add title "Waiting for summary {}..."

**Comment by InAnYan** [comment]
Huh? That's strange, it's wrong. It was there!

The only thing I removed is the text below... haha

**Comment by koppor** [comment]
At 0dee63103059e7f461b37f6129a05ad857c375ec, it is back. Thus closing.
