### ISSUE TITLE
Always use expanded form

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#131]
`doesn't` -> `does not`

No\ summary\ can\ be\ generated\ for\ entry\ '%0'\ as\ the\ database\ doesn't\ have\ path=No summary can be generated for entry '%0' as the database doesn't have path

If possible, also fix the other three unrelated translations.

**Comment by InAnYan** [comment]
Is it okay to use expanded form in non-localized strings (in logs)?

**Comment by InAnYan** [comment]
Oh, I wanted to ask "is it okay to use **non-expanded form**.

But now I see, understood

**Comment by InAnYan** [comment]
I changed all (probably all) text to expanded form (localization and LOGGER.info).

Hope I didn't miss one, and for future I will know about this
