### ISSUE TITLE
Change size to "about 400 MB"

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#143]
Do you have an idea how often the size will change?

Are there code comments pointing to the places in the code if DJL changes the default embedding model?

I think, "382" is a too fine-grained number. Remember, all texts need to be translated. And JabRef translators are lazy ^^.

![image](https://github.com/user-attachments/assets/f7335098-d334-4ccc-bd93-69390124ea82)

I would propose to use "about 400 MB"

**Comment by InAnYan** [comment]
Size won't change at all.

It depends on the selected embedding model.

Size may vary a lot, so I use `FileUtils.byteCountToDisplaySize`. Is there an internationalized method like that?

**Comment by InAnYan** [comment]
Size text is not translated. In the translation message there is `%0`, which I replace with the results of `FileUtils.byteCountToDisplaySize`

**Comment by InAnYan** [comment]
If a translated variant is still needed, then I can code "nicer" solution (like in https://github.com/InAnYan/jabref/issues/145), with "less than 50 MB", "100 MB", etc.

**Comment by koppor** [comment]
Thank you for the explanation!
