### ISSUE TITLE
Progress: Numbers should go downwards

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#145]
I changed the embedding model.

Then embeddings are regenerated (nice!)

However, the numbers jump:

![image](https://github.com/user-attachments/assets/84666eda-74f5-45e2-9256-658520d2652d)

I know, that communicating progress is very hard.

Quick win:

```
if newNumber < oldnumber
  updateProgress(newNumber)
```

Otherwise, the numbers will "jump"

More nicer solution: make intervals: 

"more than 2 minutes", "approx. 2 minutes", "approx. 1 minute", "30 seconds", "15 seconds", "5 seconds". - And map incoming numbers to that.

If easy: keep at week 1, if not easy: move to week 12.

**Comment by InAnYan** [comment]
I wrote the nicer solution :)

Besides, I put the whole progress logic in a class, what if you find it useful in some other JabRef code?

**Comment by koppor** [comment]
> I wrote the nicer solution :)

Thank you!

> Besides, I put the whole progress logic in a class, what if you find it useful in some other JabRef code?

Future work 😅. Think, this is a task... (refactoring, ...)

**Comment by koppor** [comment]
For summary of `Katz_abc` is reported for 5 seconds, even if it feels slower.

Nice feature!

**Comment by InAnYan** [comment]
Oh no, no dots...
