### ISSUE TITLE
Docs: How does the AI functionality work?

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#147]
At https://docs.jabref.org/ai#how-does-the-ai-functionality-work, the word "embedding" is missing. However, a user needs to choose an embedding model. Thus, it should be explained/mentioned/linked here, too? With "linked", I mean the heading in the documentation stating the configuration of that model.

**Comment by InAnYan** [comment]
I've added information about embeddings (https://github.com/JabRef/user-documentation/pull/499)

I think I'll close the issue and we can continue discussion of this explanation in the PR
