### ISSUE TITLE
Allow copy and paste for OpenAI token in settings

### ISSUE THREAD

**Issue by InAnYan** [InAnYan/jabref#16]
Title says everything

**Comment by InAnYan** [comment]
Previously @ThiloteE found a field that looks like a password field, but copying and pasting was allowed.

I remember they used `CustomPasswordField`, but when I used it myself, the C&P didn't work.

Unfortunately, I forgot the field that @ThiloteE found, so I need to reask.

**Comment by ThiloteE** [comment]
Under `Preferences > network > proxy configuration` there is a password field that is hidden and that allows copying and pasting into the field.

![image](https://github.com/InAnYan/jabref/assets/73715071/e67c2ea9-40d6-40d2-b08c-6d7ff4b2385d)

**Comment by InAnYan** [comment]
Thanks for remiding!

However, it doesn't work on my machine. I checked both Windows and Ubuntu version, but C&P doesn't work in the password field...

What's even more strange, I 100% remember I used this field and was able to do all the actions in this field.

@koppor Can you test this password field for proxy in "Networking" preferences tab?

Nevertheless, I created a pull request #31, where I use the same `CustomPasswordField` (that was in "Networking" tab) for OpenAI API token. Check that out too
