### ISSUE TITLE
Instead of opening a second chat window for a group, the existing one should be focussed

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#164]
![image](https://github.com/user-attachments/assets/641336d9-a2df-4bce-bfc2-8eb9971ee7de)

PR https://github.com/JabRef/jabref/pull/11666

**Comment by InAnYan** [comment]
I did some crazy coding!

Seems to work all right

**Comment by koppor** [comment]
I did not formulate right.

1. Group "A". Chat with group --> should open chat window for Group A
2. Group "A". Chat with group --> should focus existing chat window
3. Group "B". Chat with group --> should open new chat window. This time for Group B
4. Group "A". Chat with group --> should focus existing chat window (for Group A)
4. Group "B". Chat with group --> should focus existing chat window (for Group B)

**Comment by InAnYan** [comment]
Closing as fixed. This time I understood you correctly
