### ISSUE TITLE
Progress indicator jumps

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#166]
![image](https://github.com/user-attachments/assets/1c6ce6bb-e730-4061-a3c4-ff333a322e22)

Maybe, there should be a global task for the group chat waiting for injection? Started before all the tasks and closed afterwards? Just for loading indication?

Refs https://github.com/InAnYan/jabref/issues/165

Refs https://github.com/JabRef/jabref/pull/11666

**Comment by InAnYan** [comment]
How exactly progress indicator jumps? Backwards/forward?

How did you expect it to jump? 

> global task for the group chat waiting for injection

Intesting idea

**Comment by koppor** [comment]
> How exactly progress indicator jumps? Backwards/forward?

Fills, then back. Fills, then back.

Seems like only five tasks are executed in parallel. If one is finished, the next is added.

Just try with 100 PDFs.

> How did you expect it to jump? 

If JabRef says: I index 100 PDFs, then the progress should increase by each PDF. And not jump to 60% if 5 of the 100 are indexed.

**Comment by InAnYan** [comment]
Ahhh I see, a thread pool......

Okay, the idea of a one task for full group is good

**Comment by InAnYan** [comment]
Phew...

It was a challenge.

Should work properly

**Comment by koppor** [comment]
State of today

![image](https://github.com/user-attachments/assets/f0786e7c-4958-4aef-b294-5b217a17b28f)


I don't see any more which files are indexed. - Can the filename be shown in the status (11 out of 35 ..; currently: abc.pdf)? Or at the task name (Indexing for ... - abc.pdf)

**Comment by InAnYan** [comment]
Which file is indexed right now? Yes it can be, 5 files are ingested at once, so:

1) Should I list all 5 files
2) or process only one file at a time (that may be better if user has some other background tasks)

**Comment by koppor** [comment]
> Which file is indexed right now? Yes it can be, 5 files are ingested at once, so:
> 
>     1. Should I list all 5 files

- Option 1: The first and then `, ...`
- Option 2: The largest and then `, ...`

>     2. or process only one file at a time (that may be better if user has some other background tasks)

No. We should make use of our multi corse.

**Comment by InAnYan** [comment]
Should be implemented

**Comment by koppor** [comment]
text cut off, but this is OK

![image](https://github.com/user-attachments/assets/6fd56d90-ebd5-411c-9b8e-1694dfcfd728)

Wider window:

![image](https://github.com/user-attachments/assets/7af633ab-dfb5-4cbc-8cd6-96a70c85a23f)
