### ISSUE TITLE
Chat should be kept when renaming a group

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#170]
I renamed my group "XACT" to "XACT2"

![image](https://github.com/user-attachments/assets/2c7a05a0-9dd1-445e-9b55-24aaab6f8b22)

Then, the chat window was empty

![image](https://github.com/user-attachments/assets/204e614f-8c79-4e52-89fc-c053d2e171e3)

When creating a new group with the name "XACT", it is also empty.

When renaming "XACT2" back to "XACT", the chat is there again.

Refs https://github.com/JabRef/jabref/pull/11666

**Comment by InAnYan** [comment]
oh it's must, not should :)

**Comment by InAnYan** [comment]
Made a push for fixing this
