### ISSUE TITLE
Notifcations should be scrollable.

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#173]
I have dozens of notifications.

They render strange:

![image](https://github.com/user-attachments/assets/b091596c-609b-43d7-afc7-505699d5bb7c)

If this cannot be fixed easily, maybe, it is better to link to the event log

![image](https://github.com/user-attachments/assets/d40fe484-ca69-4022-b1fb-adce67e71eff)

It shows the issues already

![image](https://github.com/user-attachments/assets/12a12a6a-e808-411e-a9a9-ab5328ac1d96)

it maybe, one can limit the number of errors?

Refs https://github.com/InAnYan/jabref/issues/168

**Comment by InAnYan** [comment]
Ahahahahha

My bad.

Just a small fix is needed to limit the maximum length of a popup

**Comment by InAnYan** [comment]
I fixed this, but forgot to close the issue.

Maybe you can test? Is it okay?

**Comment by koppor** [comment]
Works

![image](https://github.com/user-attachments/assets/4e3bcba6-41bd-478f-8c33-e38877565c91)
