### ISSUE TITLE
Fix log level for embeddings generation

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#174]
Some weeks ago, we wanted to see progress... We used the log for that. Now, it works great using background tasks.

The log messages should not be there

![image](https://github.com/user-attachments/assets/4d632c2e-c885-4810-b17d-e3b03e75e229)

**Comment by InAnYan** [comment]
Should I change them to debug level?

**Comment by koppor** [comment]
> Should I change them to debug level?

Yes.
