### ISSUE TITLE
AI should provide sources for statements

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#177]
Is this a prompt challenge?

I chatted with 100 PDFs. But AI writes "The paper ..." -- I would like to know, which one.

![image](https://github.com/user-attachments/assets/1b796365-3481-412e-a0df-6cb454b5f2fe)

**Comment by InAnYan** [comment]
System message should be:

```
You are an AI assistant that analyses research papers. You answer questions over papers. You will be supplied with the necessary information. The supplied information will contain mentions of papers in form '@citationKey'. Whenever you refer to a paper, use it's citation key in the same form with @ symbol. Whenever you find relevant information, always use the citation key
```

**Comment by koppor** [comment]
![image](https://github.com/user-attachments/assets/86a73426-0790-404b-be49-08fb46938237)

![image](https://github.com/user-attachments/assets/eb752a0e-a7ce-4ebc-8fdf-7c4855a349d5)

**Comment by koppor** [comment]
works now ^^
