### ISSUE TITLE
Cannot debug JabRef on Windows in IntelliJ IDEA

### ISSUE THREAD

**Issue by InAnYan** [InAnYan/jabref#5]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Debug JabRef in IntelliJ IDEA

### Appendix

The exact error the IDE gave me is:
```
CreateProcess error=206, The filename or extension is too long
```

**Comment by koppor** [comment]
Which version of the IDE?

I think, I had the error with 2024.1.1, but I did not see it with 2024.2 EAP.

**Comment by koppor** [comment]
The solutions at https://stackoverflow.com/questions/69376895/createprocess-error-206-the-filename-or-extension-is-too-long did not solve the issues with 2024.1.1

**Comment by koppor** [comment]
Links:

- https://blog-jetbrains-com.translate.goog/idea/2017/10/intellij-idea-2017-3-eap-configurable-command-line-shortener-and-more/?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=de&_x_tr_pto=sc
- https://www.jetbrains.com/help/idea/run-debug-configuration-java-application.html#more_options

---

Plugin:

- META: https://plugins.gradle.org/search?term=createprocess+error%3D206
- https://plugins.gradle.org/plugin/ua.eshepelyuk.ManifestClasspath - seems to be unmaintained (link points to gatling which is something completely different)
- https://plugins.gradle.org/plugin/com.redock.classpathtofile
  - Does not work with recent gradle versions: https://github.com/redocksoft/classpath-to-file-gradle-plugin/issues/2
- https://plugins.gradle.org/plugin/com.virgo47.ClasspathJar
  - https://github.com/virgo47/gradle-classpath-jar-plugin
- https://plugins.gradle.org/plugin/com.github.ManifestClasspath
  - https://github.com/viswaramamoorthy/gradle-util-plugins

**Comment by InAnYan** [comment]
IntelliJ IDEA 2024.1
Windows 11

IntelliJ IDEA 2024.2 EAP does not work too.

Unfortunately, there are some issues with YouTrack account system. It says: "Invalid request, try again". I'll try to register and respond tomorrow

**Comment by koppor** [comment]
I tried to fix https://github.com/redocksoft/classpath-to-file-gradle-plugin/issues/2.

Please try to

... "publish" the updated plugin:

1. `git clone https://github.com/koppor/classpath-to-file-gradle-plugin.git`
2. `cd classpath-to-file-gradle-plugin`
3. `git checkout update`
4. `gradlew publishToMavenLocal`

... make the plugin available to gradle:

1. Open IntelliJ JabRef project
2. Patch `settings.gradle` - add that in the beginning

	```diff
	+ pluginManagement {
	+     repositories {
	+         mavenLocal()
	+         gradlePluginPortal()
	+     }
	+ }
	```
3. Patch `build.gradle`; add to `plugins`

```groovy
    id 'com.redock.classpathtofile' version '0.1.0'
```

**Comment by koppor** [comment]
@InAnYan Double check: Where is JabRef checked out? Is it `c:\git-repositories\JabRef` or do you use another folder?

**Comment by InAnYan** [comment]
@koppor Did you mean `gradle` or `gradlew`? There is no command `gradlew` on Ubuntu. I've installed `gradle` package, but it also doesn't contain `gradlew`.

Here are the results of running `gradle`:
```
ruslan@ruslan-xubuntu:~/Downloads/classpath-to-file-gradle-plugin$ gradle publishToMavenLocal
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToMavenLocal' not found in root project 'classpath-to-file-gradle-plugin'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

Here are `gradle tasks --all`:
```
ruslan@ruslan-xubuntu:~/Downloads/classpath-to-file-gradle-plugin$ gradle tasks --all
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0

> Task :tasks 

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'classpath-to-file-gradle-plugin'.
components - Displays the components produced by root project 'classpath-to-file-gradle-plugin'. [incubating]
dependencies - Displays all dependencies declared in root project 'classpath-to-file-gradle-plugin'.
dependencyInsight - Displays the insight into a specific dependency in root project 'classpath-to-file-gradle-plugin'.
dependentComponents - Displays the dependent components of components in root project 'classpath-to-file-gradle-plugin'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'classpath-to-file-gradle-plugin'. [incubating]
projects - Displays the sub-projects of root project 'classpath-to-file-gradle-plugin'.
properties - Displays the properties of root project 'classpath-to-file-gradle-plugin'.
tasks - Displays the tasks runnable from root project 'classpath-to-file-gradle-plugin'.


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

**Comment by InAnYan** [comment]
@koppor I'm so sorry. The error is gone 😆

**Comment by koppor** [comment]
> @koppor I'm so sorry. The error is gone 😆 

Like here 😅

Anything you remember? Updating? Checking out again? Updating dependencies? Maybe it could be that using the EAP version and merging in main could have lead to regenerating the configuration in a "good" way.

**Comment by InAnYan** [comment]
I remember I update to 2024.1.2, but the problem was still there. EAP had the problem too. Discovered this a

**Comment by koppor** [comment]
Ah, the error reappeared (not gone anymore)? Which means https://github.com/InAnYan/jabref/issues/5#issuecomment-2156403493 is outdated.

Then try https://stackoverflow.com/a/74816455/873282

Please try the solutions as otherwise you cannot develop properly, can you?

**Comment by InAnYan** [comment]
No, no, I mean, I asked, what actions I did. Like, I did nothing, the problem was everywhere, but one day it gone.

Subhramit has this problem

**Comment by InAnYan** [comment]
No the issue is there 😢.

I have this error while running `gradlew publishToMavenLocal`:
```
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not isolate parameters org.jetbrains.kotlin.gradle.internal.transforms.BuildToolsApiClasspathEntrySnapshotTransform$Parameters_Decorated@3fd5e9b1 of artifact transform BuildToolsApiClasspathEntrySnapshotTransform
   > Could not isolate value org.jetbrains.kotlin.gradle.internal.transforms.BuildToolsApiClasspathEntrySnapshotTransform$Parameters_Decorated@3fd5e9b1 of type BuildToolsApiClasspathEntrySnapshotTransform.Parameters
      > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 19s
3 actionable tasks: 3 executed
```

**Comment by koppor** [comment]
> 
>       > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

Seems like an exercise how to use Google? 😅

Blind guess without Google: Does your JAVA_HOME variable point to a valid JDK path?

**Comment by koppor** [comment]
> Subhramit has this problem

Update in today's DevCall: The solution of https://stackoverflow.com/a/74816455/873282 really works

![image](https://github.com/InAnYan/jabref/assets/1366654/ca27dea7-9ecb-479e-98af-4b5b91016f05)

**Comment by koppor** [comment]
> Blind guess without Google: Does your JAVA_HOME variable point to a valid JDK path?

Not needed any more. One can use the newest release of the plugin - see https://github.com/redocksoft/classpath-to-file-gradle-plugin?tab=readme-ov-file#installation for details. -- We should try this.

**Comment by koppor** [comment]
Without the plugin, it is even worse:

```
koppor@DESKTOP-KAK953S MINGW64 /c/git-repositories/jabref (ai-1)
$ ./gradlew run
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Project : => 'org.jabref' Java module

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\OpenJDK\jdk-21.0.2\bin\java.exe'' could not be started because the command line exceed operating system limits.
```

**Comment by koppor** [comment]
The workaround to compile and run with IntelliJ (and not gradle) should be tried. See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html for details.

**Comment by InAnYan** [comment]
😢 
UPDATE: Now running JabRef works.

However, debugging fails with the same error

**Comment by koppor** [comment]
> However, debugging fails with the same error
I assume you are trying to debug with gradle. Please try to debug with the IntelliJ compiler. Link is in the comment https://github.com/InAnYan/jabref/issues/5#issuecomment-2178233951.

**Comment by InAnYan** [comment]
> The workaround to compile and run with IntelliJ (and not gradle) should be tried. See [devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html) for details.

:cry: again `langchain4j`

![изображение](https://github.com/InAnYan/jabref/assets/13097618/e03025e8-43a3-4e64-a3c1-70c0031f1053)

**Comment by InAnYan** [comment]
Oliver, let's forget this, I don't want to distract you with updates.

The error appeared again, I can't even run JabRef.

I'll just try to make run Skype on Linux better

**Comment by koppor** [comment]
Current state: At the PR https://github.com/JabRef/jabref/pull/11430, `./gradlew run` does not work. Thus, we need to fix the gradle run thing.

(And IntelliJ can come later. We should have Gradle working. One can also run using gradle in intellij, which is the default setup. Only in advanced setup, one uses IntelliJ to run the thing. See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html)

**Comment by InAnYan** [comment]
https://pad.riseup.net/p/jabref-ai-console

**Comment by InAnYan** [comment]
1. Some gradle plugins returned non zero exit value. When I was experimenting with logs, it turns out that they can't find "org.jabref" module. Is there any solution for that?
2. I've also found the command line that is executed. I've pasted it in rise up pad. Oliver, maybe it can give you some hints on how to reduce it?
3. I've tried several main solutions, but in the end they didn't work. I still have some to try.
What's interesting, when I turned off command line limits in some windows system settings, the error is still there but it has different message. I also remember that there is a parameter about "dynamic.classpath" in "workspace.xml". But..... I can't edit the file, IntelliJ would just delete my setting. I tried to edit the file externally, but it deletes the line with "dynamic.classpath" too. Oliver, I remember you told that it works, how did you do that?

**Comment by koppor** [comment]
@InAnYan I still don't have a reply to my comment two weeks ago: https://github.com/InAnYan/jabref/issues/5#issuecomment-2178233951

Maybe I have to rephase: One can run with gradle. One can also run with IntelliJ.

Two questions:

1. How is your system configured?\\
    ![image](https://github.com/InAnYan/jabref/assets/1366654/2ca3a9ca-f8e2-4694-9577-d713de94f08e)
2. What happens if you change to IntelliJ?  See https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html for instructions

**Comment by koppor** [comment]
- [ ] Blocked by https://github.com/redocksoft/classpath-to-file-gradle-plugin/pull/7.

**Comment by InAnYan** [comment]
> @InAnYan I still don't have a reply to my comment two weeks ago: [#5 (comment)](https://github.com/InAnYan/jabref/issues/5#issuecomment-2178233951)
> 
> Maybe I have to rephase: One can run with gradle. One can also run with IntelliJ.
> 
> Two questions:
> 
>     1. How is your system configured?\
>        ![image](https://private-user-images.githubusercontent.com/1366654/345588428-2ca3a9ca-f8e2-4694-9577-d713de94f08e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzgzNTIsIm5iZiI6MTcyMDA3ODA1MiwicGF0aCI6Ii8xMzY2NjU0LzM0NTU4ODQyOC0yY2EzYTljYS1mOGUyLTQ2OTQtOTU3Ny1kNzEzZGU5NGYwOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDcyNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMyMzBkNDIzMjA0NmFhNTBjZDEzMzdjOWJjNDlhN2FiYjc3ZTk3MzQwNDlmZDNjYjViYjFiNmIwMmNjMjA1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fObewm0273jtMZAqahhhrq8BdjdnXaJ0A0QNko-kyDI)
> 
>     2. What happens if you change to IntelliJ?  See [devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html) for instructions

Ah, I remember, it was the time where the issue just gone. Need to try this method

**Comment by InAnYan** [comment]
![изображение](https://github.com/InAnYan/jabref/assets/13097618/9731b195-f7f0-403d-898d-248efccef5e4)

**Comment by InAnYan** [comment]
yeah, and I don't have `out` dir in `build/resources/main`

**Comment by koppor** [comment]
I could not get `--patch-module` working inside IntelliJ (refs https://youtrack.jetbrains.com/issue/IDEA-273668/javac-patch-module-compiler-flag-does-not-work). Thus, I am waiting for the fix https://github.com/langchain4j/langchain4j/issues/1066. Then, compilation using IntelliJ should work without issues. Then, debugging is also possible.

**Comment by InAnYan** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/13097618/345738005-9731b195-f7f0-403d-898d-248efccef5e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODUxMTUsIm5iZiI6MTcyMDA4NDgxNSwicGF0aCI6Ii8xMzA5NzYxOC8zNDU3MzgwMDUtOTczMWIxOTUtZjdmMC00MDNkLTg5OGQtMjQ4ZWZjY2VmNWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MjAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNmNkN2QzZDZkNjVhMWRhZGQxYTdiOGRjYzQ4NWIwZmNhYzVlNjk1YThlNzVlZDNjNjVjMjY4YzdlMTgyMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.urY1xDQ6-DMHD_urH9P5P-JVRqjYNxzNcc2LUtbrfDY)
> 
> There is context missing for this. I assume, you are at another branch (NOT `ai-pr-1`). You seem to have added new dependencies. Does your code compile in IntelliJ? Is `intellij-12-build.md` updated?

No, no, it's the ai-pr-1

Sorry, should've mentioned: I've followed the https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-89-run-with-intellij.html and couldn't build the project

**Comment by koppor** [comment]
The issue title is very generic. With gradle, it should work now. Please check (on the `ai-pr-1` branch). Double check that gradle is used as build tool.
