### ISSUE TITLE
Priority for selected entry

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#52]
When indexing a large library - and the user focuses an entry, there is a "Please wait" message shown (https://github.com/InAnYan/jabref/pull/48). If I am at the end of a large library, this takes long. Thus, it would be nice if the PDFs of the current entry would "jump" the queue.

More background on priority queue (and how not to visualize it): https://www.linkedin.com/feed/update/urn:li:activity:7206148259189301248?updateEntityUrn=urn%3Ali%3Afs_feedUpdate%3A%28V2%2Curn%3Ali%3Aactivity%3A7206148259189301248%29

**Comment by koppor** [comment]
DevCall: Looks good. Please be aware of concurrency. I think, a `synchronized` block is needed for both reading and writing to the stack.

Pseudo code:

if element in stack
  remove
  add on top

(these are three operations, which all should executed in one block and not interrupted)

**Comment by InAnYan** [comment]
The solution I proposed in stack seems not to work(

**Comment by koppor** [comment]
> The solution I proposed in stack seems not to work(

More details please. 😅 Is there a MWE to check? Maybe a branch to try out?

**Comment by InAnYan** [comment]
Embedding generation is now on demand
