### ISSUE TITLE
Properly handle errors with MVStore

### ISSUE THREAD

**Issue by InAnYan** [InAnYan/jabref#62]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

...

**Comment by InAnYan** [comment]
Here is how currently it is managed in #fix-for-51:

![изображение](https://github.com/InAnYan/jabref/assets/13097618/5ff9cb1b-aebd-47aa-a17d-1834078cad94)

Unfortunately there is no way to tell user of this error with DialogService because it is not initialized.

I don't like this approach because the AiService will then store messages in memory, and then when user exists, they will be confused "where my messages go?". I doubt they read logs

**Comment by InAnYan** [comment]
Another nasty thing:

![image](https://github.com/InAnYan/jabref/assets/13097618/68ae5e1f-9d1b-4bc3-bb12-99b46b5c9a99)

It happens in background process, so I guess, there is nothing we can do?

**Comment by koppor** [comment]
> It happens in background process, so I guess, there is nothing we can do?

It did not appear any more, did it?

**Comment by InAnYan** [comment]
Closed, as I added `dialogService` there.

Also there is no way to catch this `BackgroundWriter` errors

**Comment by koppor** [comment]
> Also there is no way to catch this `BackgroundWriter` errors

Please add a reference to the code here. It is difficult for me to judge.

If you mean BackgroundTask, there is `onError`. I want to check where you call MVStore how. Another kind of BackgroundWriter could be a reason for https://github.com/InAnYan/jabref/issues/77.

**Comment by InAnYan** [comment]
No, from the `MVStore` docs: it runs once in a while a `BackgroundWriter` to synchronize MVStore with filesystem.

And so, there is no way to catch errors from `BackgroundWriter` (they are also `RuntimeException`s):
1. `BackgroundWriter` is not called by our code.
2. You provided me with a clever notice about `onError`, but unfortunately `MVStore` doesn't provide any `onError` callback.
