### ISSUE TITLE
Having no Citationkey then adding one is not enough to start chatting

### ISSUE THREAD

**Issue by ThiloteE** [InAnYan/jabref#69]
### JabRef version

5.13 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### How to reproduce:

1. Have entry without citationkey
2. Add pdf
3. Open Entry editor --> Open AI tab --> see message that one has to add a citationkey to the entry, otherwise AI chat is not possible.
4. Create ciationkey to entry

### Expectation:

Now it is possible to chat with AI

### Reality:

AI chatting is not possible.
Following message shows:
![image](https://github.com/InAnYan/jabref/assets/73715071/b5f57596-3762-4078-b2a2-cd4fba483c7a)

**Comment by InAnYan** [comment]
Solved!!!!
