### ISSUE TITLE
JabRef does not shutdown at all after interacting with OpenAI

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#77]
(see title)

---

- refs https://github.com/square/okio/issues/738

**Comment by koppor** [comment]
VisualVM shows

![grafik](https://github.com/InAnYan/jabref/assets/1366654/e6089ae4-a746-413d-b35a-9c46b6cc352b)

One cannot shutdown OkHttp using a parameter. See https://github.com/square/okhttp/issues/6173.

**Comment by koppor** [comment]
I think, I found the root cause: https://github.com/langchain4j/langchain4j/pull/1449

**Comment by koppor** [comment]
Waiting for 60 seconds, the tasks are like this:

![image](https://github.com/user-attachments/assets/cb02acb5-0cc5-4f17-b69f-37571e63b148)

**Comment by koppor** [comment]
JabRef running (on main branch)

![image](https://github.com/user-attachments/assets/60241fe8-61c9-4e7f-8b09-783535563a82)

**Comment by koppor** [comment]
New threads after inputting a message:

![image](https://github.com/user-attachments/assets/90669d02-0971-4780-abee-ee32695ac411)

pool-4-thread-1, pool-8-thread-1, and pool8-thread-2 are new.

**Comment by koppor** [comment]
Opening Tab only:

**Comment by koppor** [comment]
Next step: Find out what is this `pool-4-thread-1`:

![image](https://github.com/user-attachments/assets/6e81b7d1-888a-451d-8dbc-ad170e935b69)

**Comment by koppor** [comment]
Current state: This thread is created at `dev.langchain4j.chain.ConversationalRetrievalChain#execute`. Need to dive more into it.

**Comment by InAnYan** [comment]
@koppor thank you very much for the findings!!!

Will also try to investigate it!

**Comment by koppor** [comment]
To searcha for the thead starter, Byteman could be used. Source: https://stackoverflow.com/a/78051083/873282

However, I do not know at all how to start with Gradle. -- Maybe it is very simple: pass the `JAVA_TOOL_OPTIONS` using IntelliJ somehow.
