### ISSUE TITLE
Update to langchain 0.33

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#89]
Langchain 0.33 solved the issue of split packages - https://github.com/langchain4j/langchain4j/releases/tag/0.33.0

We should get this in, so that we can remove the workarounds in build.gradle and IDE setup. (And if we still need some workarounds, we need to check whether to report upstream - or if it is an issue of the JabRef setup)

**Comment by InAnYan** [comment]
whoa

**Comment by InAnYan** [comment]
OMG, it works
without anything...
