### ISSUE TITLE
Inform LLM about the entry

### ISSUE THREAD

**Issue by InAnYan** [InAnYan/jabref#91]
Put various metadata about BIB entry to the system message (or maybe not the system message) of model, so it will know the name of paper, their authors, year, etc.

**Comment by koppor** [comment]
You can render the full reference. Maybe using the current entry preview? Or some default preview? This takes care about all edge cases of fields existing...

I know, that "title: {}, author: {}" would be even mroe nice for the AI. I do not know, how much impact that will have. (I would "just" put: "first author et al", title, year. Maybe journaltitle/booktitle if presetn. Don't overthink.)

**Comment by ThiloteE** [comment]
System message controls how the model speaks. You don't want your llm to think it is the author in question.

This is a typical system prompt:

![image](https://github.com/user-attachments/assets/3fc13138-34c0-4955-a0b6-e53f0681b698)

**Comment by ThiloteE** [comment]
So the overall structure could look something like this:

1.System: Below is an instruction that describes a task. Write a response that appropriately completes the request using the following context: {metadata} + {RAG data from PDF}.
2. User Instruction.
3. Model response.

**Comment by koppor** [comment]
> System message controls how the model speaks and how it behaves.
> This is a typical system prompt:
> 
> ![image](https://github.com/user-attachments/assets/3fc13138-34c0-4955-a0b6-e53f0681b698)
> 

Note that there is already a preference for that inside JabRef.

**Comment by InAnYan** [comment]
I've implemented this.

I will close this, as it's easy to test: "What is the title of the paper?", "Who are the authors?", etc.
