### ISSUE TITLE
Fix privacy policy for AI summarization

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#92]
![image](https://github.com/user-attachments/assets/a2e6cb75-39fd-46ed-a3f1-1f9a0bd2ca22)

- [x] (1) shows "AI summary", but (2) shows "chatting". Is the Privacy Policy right?
- [x] (3) shows missing dots. Please add a dot after each sentence.
- [x] If possible, there should a link to "Deep Java Library" in the privacy policy
- [x] Add information how much will be downloaded (300 MB?)

**Comment by InAnYan** [comment]
DJL said that the downloads are anonymous and no data is collected. Is that okay to mention in Privacy Policy?

**Comment by InAnYan** [comment]
For downloading size: it depends on selected embedding model and, I'm not sure of a way to estimate download size... Different models weight differently

**Comment by koppor** [comment]
> DJL said that the downloads are anonymous and no data is collected.

Via email?

Can you ask them if it was OK to make that email public?

> Is that okay to mention in Privacy Policy?

We need to have a "trusted" source. If a company sues JabRef e.V. we need to make sure that we did our best to ensure that the statements we do are true. If we just say: "It was claimed privately to some of our contributors", this is not enough.

It is still bad that they don't have a privacy policy, but we need to accept.

The alternative is that we mirror the models...

**Comment by koppor** [comment]
> For downloading size: it depends on selected embedding model and, I'm not sure of a way to estimate download size... Different models weight differently

Just estimate 1 GB download size for each. 

Alterntive:

1. HTTP allows to get the file size before downloading: https://stackoverflow.com/questions/122853/how-to-get-the-file-size-from-http-headers -- Maybe, the servers of them report the size back
2. hard-coded store the current known size inside jabref. At runtime, look it up. 😅

**Comment by InAnYan** [comment]
https://github.com/deepjavalibrary/djl/discussions/3370#discussioncomment-10233632

What should we do?

**Comment by koppor** [comment]
> [deepjavalibrary/djl#3370 (comment)](https://github.com/deepjavalibrary/djl/discussions/3370#discussioncomment-10233632)
> 
> What should we do?

We can link these statements.

**Comment by InAnYan** [comment]
Nearly got mad.

Neither it's understandable how they download models from the code,

neither from Wireshark....

I guess hardcoded values would be better. Embedding model is not something that is actively updated. If it's updated, that would be a new model

**Comment by InAnYan** [comment]
Phew, what do you think of recent push?

**Comment by koppor** [comment]
It is OK. However, consistency is an issue. I think, I did not tell often enough that consistency in a UI is important.

![image](https://github.com/user-attachments/assets/872aa6a1-7fd7-4fae-8db1-0db7b61a6cc7)

- [ ] Change the sentence to: "You find information about the privacy policy here". 

Then, it is somehow similar to the sentences above, even if all text is blue. This is OK. On the first look, the new proposed sentence is similar to the other ones.

- [ ] Add a space after the sentence before. Currently, there is no space between the dot and the link.

**Comment by koppor** [comment]
Moved to week 1, because the "Privacy notice" also appears at "AI chat"

**Comment by InAnYan** [comment]
>  Change the sentence to: "You find information about the privacy policy here".

I thought about that, was a little worried, that user will expect link after word "here"

**Comment by InAnYan** [comment]
I think I'll close the issue, as I fixed everything you wrote
