### ISSUE TITLE
Refine"by AI"

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#93]
1. I started JabRef
2. I opted in to AI (refs https://github.com/InAnYan/jabref/issues/92)
3. I am waiting for the summarization

![image](https://github.com/user-attachments/assets/0c2d4a7e-718e-4cd9-a9bd-0ba4fd0f2eb2)

The text "AI" is not clear. The privcacy policy stated, one can choose between Misral, OpenAI, and others. The status output should say with which provider JabRef is interacting.

**Comment by InAnYan** [comment]
Implemented
