### ISSUE TITLE
Add more user logs

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#95]
Use `LOGGER.info` more often. These will appear at 

![image](https://github.com/user-attachments/assets/f075352d-0d46-4612-a137-60c4fbd0d2a5)

Currently, I am waiting for the summary. How many hours should I wait?

![image](https://github.com/user-attachments/assets/de3e5f22-996b-458d-965b-dc91f6e152cd)

**Comment by InAnYan** [comment]
I've added progress indication for this.

Should I add `LOGGER.info` too?

**Comment by koppor** [comment]
Do you have a screenshot? Here, it renders as follows:

![image](https://github.com/user-attachments/assets/d62a1f17-0c53-4215-91bf-c19f0ed893d9)

`LOGGER.info` is nice. We can still turn it into `LOGGER.debug` if users start complaining.

Currently, it is hard to see what's happening.

**Comment by InAnYan** [comment]
No, I mean, I've added progress indication: https://github.com/InAnYan/jabref/issues/101

What kind of `LOGGER.info` should I add and where?

**Comment by koppor** [comment]
> No, I mean, I've added progress indication: #101

That issue is about indexing. Here, I talk about "Processing".

> What kind of `LOGGER.info` should I add and where?

I report from a user perspective.

At each time, a thing could last more than 10 seconds, there should be a LOGGER.info. (This is the poor man's solution for progress, but also offering some details to allow users to understand, what is going on)

1. Model download (This relates to https://github.com/InAnYan/jabref/issues/105)
2. Model download finished  (This relates to https://github.com/InAnYan/jabref/issues/105)
3. Sending a file for indexing to the AI provider: File {} is sent to {}. Show the URL. (This is this issue)
4. Sending a file for summarization to the AI provider: File {} is sent to {}. Show the URL. (This is this issue)
5. Sending a question to the AI provider: Request sent to {}. Show the URL. -- Maybe, this can be LOGGER.debug as this does not cause huge waiting issues.

---

More motivation: I am now waiting for a long time for "Downloading...", but there is nothing transferred:

![image](https://github.com/user-attachments/assets/af020a01-3873-465c-8b42-f6b86813d4a5)

![image](https://github.com/user-attachments/assets/17e7d439-fd75-4a7f-a3ae-b539aa7ace2c)`

![image](https://github.com/user-attachments/assets/1a3865ed-dd5a-438c-83c1-56c0f4fe940c)

How can I know what is going wrong?

With some more logging, I hope, it can be known.

**Comment by InAnYan** [comment]
What do you think about this: https://github.com/JabRef/jabref/commit/f79f87462b527a70cfa0db697ad1b16b88a0eb5f ?

(Hope this time I sent you the right commit :) )

**Comment by koppor** [comment]
If possible, add the citation key to the log message.

Two reasons:

1. As a user, I don't rember half an hour later what I did (I think, I wrote that somewhere else 😅)
2. As user, I work in parallel with multpile documents, it is not clear, which log message correlates to which action

```
INFO: Summary of the file was generated successfully
INFO: Sending request to AI provider to summarize a chunk
INFO: Summarizing chunks (1 pass)
```

Line 2 should also include the URL as written in my last comment above (https://github.com/InAnYan/jabref/issues/95#issuecomment-2269233231)

Good example:

    INFO: Finished summarization task for entry Corti_2009

**Comment by InAnYan** [comment]
Should that URL be full API endpoint? I don't think there is a way to extract it. Moreover, it's a POST request, so nothing fancy in the URL.

What I can show is only the API base URL

**Comment by InAnYan** [comment]
Added more in: https://github.com/JabRef/jabref/pull/11430/commits/3b2887b389d96c2328a3d4c3021e1a69f1f38734

**Comment by koppor** [comment]
> What I can show is only the API base URL

Base URL is good enough!

This contributes to transparency which data is sent to where.

**Comment by InAnYan** [comment]
Okay then, I'll close the issue. Base URL is shown
