### ISSUE TITLE
Fix preferences for AI

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#98]
![image](https://github.com/user-attachments/assets/3714ac14-7df2-406a-acc0-dbaa4a3231e6)

- [x] (1) I did not enter any API token for Hugging face - the field should be empty then? --> Each API provider has a different token - thus, this field should be dependend on the provider
- [x] (2) Rename to "Enable customizing expert settings" - The current text is a bit misleading, because choosing an "AI provider" is also an "AI setting" IMHO, which one customized
- [x] If I change the API entpoint of misral, change back to OpenAI above and change back, my new value is lost - some old value is displayed

Dialog does not store misral URL

![image](https://github.com/user-attachments/assets/adf600d0-3044-4c47-b159-95ff9f126f1c)

"Save"

Open again - OK

Change to "OpenAI"

Change back to "Misral"

Old URL there:

![image](https://github.com/user-attachments/assets/b452ec40-5722-4d28-bc9c-2394508e9a7d)

**Comment by ThiloteE** [comment]
- [ ] (2)

   > "Enable customizing expert settings"

   This is not good English. "Use custom settings" would be better. Or alternatively "Customize expert settings" or "Enable custom settings". I asked a native US-English speaker.

- [ ] (4)

   "These parameters affect how AI will answer your questions" --> rename to --> "These parameters affect how **the** AI will answer your questions."

**Comment by InAnYan** [comment]
For the third point: What is the best way to do this?

The situation is: a user has filled a custom API endpoint, but then they switch to other AI provider.

I see there two options:
1) [Current option] We replace custom values with default ones every time the AI provider is switched

Rationale: what if users switches provider, but forgets to change the API URL?

2) For each of the provider, store their custom API URL. <------------- should this be chosen?

**Comment by InAnYan** [comment]
This also concerns API token:

Should it be custom for every type of AI provider, or any time we change AI provider it becomes empty?

**Comment by koppor** [comment]
I run now - commit [e1a895bf9f4b6a3ebdc362735a7ec2d1e7b2c1b9](https://github.com/JabRef/jabref/commit/e1a895bf9f4b6a3ebdc362735a7ec2d1e7b2c1b9)

- [ ] From Thilo (https://github.com/InAnYan/jabref/issues/98#issuecomment-2266185611), "Customize AI settings" still has to be renamed to "Customize expert settings"
- [ ] From Thilo (https://github.com/InAnYan/jabref/issues/98#issuecomment-2266185611), **the** is still missing

**Comment by koppor** [comment]
> Rationale: what if users switches provider, but forgets to change the API URL?

For that, we have "Reset expert settings to default". -- The best would be to have a reset button after the API-base URL to only reset that.

**Comment by koppor** [comment]
> 2\. For each of the provider, store their custom API URL. <------------- should this be chosen?

Yes.

We also need to work on the hiearchical display. Mac OS finder uses columsn for that: 
<img width="203" alt="Big_Sur_Finder_screenshot" src="https://github.com/user-attachments/assets/86b516e6-e659-473a-9178-79e257b8ddf5">

In JabRef, we use indent.

![image](https://github.com/user-attachments/assets/7cf4b1bc-3ec3-48c4-a2fe-641e88752746)

- [ ] Thus, "Chat model" and "API token" should have an indent"

---

I know that for "API base URL" and "Embedding model" this is currently hard.

I assume the user does not need to change the embedding model often? Although, this statement contradicts: https://github.com/InAnYan/jabref/issues/85

Maybe, "Embedding model" needs to be moved to "General" - as the user also can change the "Chat model"?

**Comment by koppor** [comment]
I reset JabRef's preferences. Why is there an API token in "OpenAI"

![image](https://github.com/user-attachments/assets/beb40074-5891-4bb4-bba0-3b7418d2b129)

**Comment by koppor** [comment]
There should be a help for "Chat model", too. -- The most hard thing (in the "easy" prefrences) is not documented 🤣🤣

![image](https://github.com/user-attachments/assets/b4f0c095-1615-4698-9d5f-3cdb7f8e51d7)

(Also, the dialog would look better, because always (?) at the right side - and not disturbed by one dropdown)

**Comment by koppor** [comment]
> Should it be custom for every type of AI provider, 

Yes.

Reason: It is very likely that I as user try more than one AI provider and fetch API keys for that. I want to switch back and forth of these providers easily.

> or any time we change AI provider it becomes empty?

No.

(Furthermore, the API key of one provider should not be shared with another provider. I think, the API key exchange is not protected similar to password exchange, but sent directly to the API provider. Thus, if I use a medium-secure AI provider, my key could get compromised by them)

**Comment by InAnYan** [comment]
Okay, I see, then for each AI provider we need to store:
- Selected chat model
- API token

Should we also store API base URL?

**Comment by InAnYan** [comment]
https://github.com/InAnYan/jabref/issues/98#issuecomment-2267432812

These points should be fixed in 637d14ef80fe8026ef722e81af734807a4dcb828

**Comment by koppor** [comment]
Reply by OpenAPI if Misral key is used:

> 401 - message: Incorrect API key provided: dWkr3jyb********************UEyx. You can find your API key at https://platform.openai.com/account/api-keys., type: invalid_request_error, param: null, code: invalid_api_key

**Comment by koppor** [comment]
> [#98 (comment)](https://github.com/InAnYan/jabref/issues/98#issuecomment-2267432812)
> 
> These points should be fixed in [637d14e](https://github.com/InAnYan/jabref/commit/637d14ef80fe8026ef722e81af734807a4dcb828)

Wrong commit link, but the two poitns are fixed

![image](https://github.com/user-attachments/assets/58bcd6f9-4306-4be5-a449-8001c096f432)

(The others are still open)

**Comment by InAnYan** [comment]
Okay, I've tried to fix this issue in recent commits...

Should (?) work

**Comment by koppor** [comment]
No.

![image](https://github.com/user-attachments/assets/95e8d582-0d28-4a56-b8c6-943316c53d0b)

![image](https://github.com/user-attachments/assets/ee3cc9a7-1664-45d3-ac5d-22374bbd5f50)

**Comment by InAnYan** [comment]
Fixed

**Comment by koppor** [comment]
No

![image](https://github.com/user-attachments/assets/83b06fcc-1cc6-4ba3-9e52-00aa845024bc)

**Comment by koppor** [comment]
547da5d020a9be673c67ca991009ee4c0c11a26a

**Comment by koppor** [comment]
Tried again with a preference reset. Keeps not working.

**Comment by InAnYan** [comment]
It's stored, but not used when you send messages.

When user turns off "customize expert settings", should they be resetted?

What if I want to customize expert settings, then turn off, then return to previous parameters that I set?

**Comment by koppor** [comment]
First of all, please try to follow me slowly. Take the time to understand.

![image](https://github.com/user-attachments/assets/3730c58f-5b5e-4de5-82c4-b7b4af7b0684)

1. First - Customize export settings are turned off
2. Second - "WHAT-THE-FUCK" is a String contained in the URL
3. Third - The AI Returns a 404, because "WHAT THE FUCK" appears in the URL

That must not happen. If the customized expoert settings are disabled, ther normal API url needs to be used

1. Open Preferences
2. Enable Custom expert settings
3. Add „WHAT THE FUCK“ to the URL
4. Save
1. Open Preferences
2. Disable Custom expert settings
3. Open “AI Summary” tab
4. Click on regenerate

**Comment by koppor** [comment]
> When user turns off "customize expert settings", should they be resetted?

No.

> What if I want to customize expert settings, then turn off, then return to previous parameters that I set?

Currently, the preference UI renders well to the user. It just does not route the setting properly to the AI code.

**Comment by InAnYan** [comment]
Okay, sorry, it should be fixed now :)

Just a small change about listening to preferences change

**Comment by koppor** [comment]
Tried. Works.
