### ISSUE TITLE
Soft wrap for error messages

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#99]
![image](https://github.com/user-attachments/assets/7dad439d-2cc2-4919-81f9-4cbbfa8783b5)

I get

> 429 - message: Rate limit reached for gpt-4o in organization org-3M84iZQTliRuKpVVeuB53iHJ on tokens per min (TPM): Limit 30000, Used 14494, Requested 16221. Please try again in 1.43s. Visit https://platform.openai.com/account/rate-limits to learn more., type: tokens, param: null, code: rate_limit_exceeded

This message is should be wrapped (and not span to the right.

**Comment by InAnYan** [comment]
Fixed
